### ISSUE TITLE
Contribution Guidelines and Project Direction

### ISSUE THREAD

**Issue by christianechevarria** [internalfx/centric-server#4]
Hello all, I can see that centric-server is an early project currently, thanks for publishing it for everyone! I'm very interested in tools of this nature and would potentially like to contribute to something like this but I had a hard time finding contribution guidelines. Does this project welcome contributions?

On another note, I'd love to learn more about where you guys might be taking the project to see if I can help in any way. I've been looking for something like what you guys are creating for a little bit, I was recently taking a look at [Huggin](https://github.com/huginn/huginn) and going into their [issues](https://github.com/huginn/huginn/issues/130) to try and find a solution to plug JS code into a web automation tool, but Huggin is completely in Ruby and it seems hairy to get it to work.

For some background, I've been very interested in making a web-enabled automation tool to potentially plug an evolutionary neural-network library I'm [working on](https://github.com/liquidcarrot/carrot) into to automate actions across different services, but haven't been able to find anything yet. Would that be a direction you might want to take the project in?

**Comment by internalfx** [comment]
@christianechevarria Thanks for your interest!

If a pull request is useful and fits in with the rest of the project I'm open to it. I would suggest asking about what it is you want to add before doing any work though. I'd hate for you to put in a bunch of work and have it not match the direction we're going in.

**Comment by internalfx** [comment]
Assuming your question is answered....
